DROP DATABASE IF EXISTS `sysubbs`;
CREATE DATABASE `sysubbs` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
USE 'mysql';
GRANT ALL PRIVILEGES ON dgist.* TO 'root'@'localhost' IDENTIFIED BY 'password' WITH GRANT OPTION;
FLUSH PRIVILEGES;