"""chagen avatar

Revision ID: 3a601043bcfc
Revises: 09a6a56392d2
Create Date: 2016-03-18 12:00:45.284071

"""

# revision identifiers, used by Alembic.
revision = '3a601043bcfc'
down_revision = '09a6a56392d2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_avatar_default', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('new_avatar_file', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'new_avatar_file')
    op.drop_column('users', 'is_avatar_default')
    ### end Alembic commands ###
