"""initial migration

Revision ID: 64f8d56c44fa
Revises: None
Create Date: 2016-03-14 09:35:34.093781

"""

# revision identifiers, used by Alembic.
revision = '64f8d56c44fa'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen')
    ### end Alembic commands ###
