"""add gravatar

Revision ID: f8374be84c67
Revises: 64f8d56c44fa
Create Date: 2016-03-14 10:00:10.536834

"""

# revision identifiers, used by Alembic.
revision = 'f8374be84c67'
down_revision = '64f8d56c44fa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
